name: Build and Push Docker

on:
    push:
      branches: [ main ]

jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dimohamdy
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dimohamdy/mcp-appstore:latest
            dimohamdy/mcp-appstore:1.0.0
